#SPDX-License-Identifier: MIT-0
---
# tasks file for install_nfs

- name: Update package cache
  apt:
    update_cache: yes

- name: Upgrade all packages to the latest version
  apt:
    upgrade: dist

- name: Install nfs server
  apt:
    name: nfs-kernel-server
    state: present
    update_cache: yes

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /srv/nfs
    state: directory
    mode: '0777'

- name: Change ownership
  ansible.builtin.command:
    cmd: sudo chmod 777 /srv/nfs

- name: Ensure NFS export is defined in /etc/exports
  lineinfile:
    path: /etc/exports
    line: "/srv/nfs    *(rw,sync,no_subtree_check,no_root_squash)"
    state: present

- name: Export the NFS shares
  ansible.builtin.command:
    cmd: exportfs -ra

- name: Restart NFS service
  ansible.builtin.systemd:
    name: nfs-kernel-server
    state: restarted

- name: Enable NFS service at boot
  ansible.builtin.systemd:
    name: nfs-kernel-server
    enabled: true